services:
  # Backend Service
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openpoll-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - openpoll-network
    restart: unless-stopped
    user: root
    command: sh -c "npm install && node node_modules/nodemon/bin/nodemon.js -L src/server.js"

networks:
  openpoll-network:
    driver: bridge
